apiVersion: v1
kind: Service
metadata:
  name: cool-app
  labels:
    app.kubernetes.io/name: cool-app
    app.kubernetes.io/instance: cool-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: cool-app
    app.kubernetes.io/instance: cool-app
